# Generated by Django 5.2 on 2025-04-23 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['aisle', 'bay']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='aisle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='bay',
            field=models.CharField(default='A1', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
