# Generated by Django 5.2 on 2025-04-26 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_options_rename_category_product_aisle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['aisle', 'bay'], 'permissions': [('can_view_product', 'Can view product'), ('can_edit_product', 'Can edit product')]},
        ),
    ]
