# Generated by Django 5.2 on 2025-04-27 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alertconfig_stockalert_stocktransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockalert',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'permissions': [('can_view_supply', 'Can view supply'), ('can_edit_supply', 'Can edit supply')]},
        ),
        migrations.RemoveField(
            model_name='location',
            name='code',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='price',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='sku',
        ),
        migrations.AddField(
            model_name='stockalert',
            name='supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='inventory.supply'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.supply'),
        ),
        migrations.AlterField(
            model_name='alertconfig',
            name='alert_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='alertconfig',
            name='threshold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='alert_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=3),
        ),
        migrations.AlterField(
            model_name='supply',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='inventory.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supply',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
