# Generated by Django 5.2 on 2025-04-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_stocktransaction_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
